name: bp_logger
description: Flutter app that logs blood pressure values in Google Drive as a Sheets file
repository: https://www.github.com/theRookieCoder/bp_logger
publish_to: "none"

version: 1.4.1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # Flutter SDK
  intl: ^0.18.0 # For datetime formatting
  url_launcher: ^6.1.9 # For opening the log file
  package_info_plus: ^3.0.2 # For getting the app version
  google_fonts: ^4.0.3 # For monospaced error font
  animated_check: ^1.0.5 # For animated checkmark
  drive_helper: ^1.4.0 # For Google Drive
  flutter_phoenix: ^1.1.1 # For restarting the app
  animations: ^2.0.7 # For Material animations

dev_dependencies:
  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.0

icons_launcher:
  image_path: "assets/Icon_298x298.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/Icon_298x298.png
