name: bp_logger
description: Flutter app that logs blood pressure values in Google Drive as a Sheets file
repository: https://www.github.com/theRookieCoder/bp_logger
publish_to: "none"

version: 1.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # Flutter SDK
  intl: ^0.18.0 # For datetime formatting
  url_launcher: ^6.1.8 # For opening the log file
  package_info_plus: ^3.0.2 # For getting the app version
  google_fonts: ^4.0.3 # For monospaced error font
  animated_check: ^1.0.5 # For animated checkmark
  drive_helper: ^1.4.0 # For Google Drive
  flutter_phoenix: ^1.1.0 # For restarting the app

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon_298x298.png"
  adaptive_icon_background: E0E0D9

flutter:
  uses-material-design: true
  assets:
    - assets/Icon_298x298.png
