name: bp_logger
description: Logs BP values in Google Drive as a Sheets file
repository: https://www.github.com/theRookieCoder/bp_logger
publish_to: "none"

# The following defines the version and build number for your application.
version: 1.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # Flutter SDK
  intl: ^0.17.0 # For datetime stuff
  googleapis: ^2.0.0 # For Google Drive and Google sign in
  google_sign_in: ^5.0.2 # For signing in to Google
  url_launcher: ^6.0.3 # For opening the log file
  package_info_plus: ^1.0.1 # For getting version for web
  google_fonts: ^2.0.0 # For monospaced font
  animated_check: ^1.0.2 # For animated checkmark

dev_dependencies:
  # flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon_498x498.png"

flutter:
  uses-material-design: true
