name: bp_logger
description: Flutter app that logs blood pressure values in Google Drive as a Sheets file
repository: https://www.github.com/theRookieCoder/bp_logger
publish_to: "none"

version: 1.5.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  url_launcher: ^6.1.9
  package_info_plus: ^3.0.2
  google_fonts: ^4.0.3
  animated_check: ^1.0.5
  drive_helper: ^1.4.0
  animations: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.0

icons_launcher:
  image_path: "assets/Icon_298x298.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/Icon_298x298.png
