name: Build Flutter app and deploy to Firebase Hosting on push

on:
  push:
    branches: '**'
    paths:
      - "**.dart"
      - "pubspec.lock"
      - "pubspec.yaml"
      - ".github/workflows/web_deploy.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build webpage
        run: |
          flutter pub get
          flutter build web --web-renderer canvaskit --release
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: build/web
          retention-days: 1
  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build-files
          path: build/web
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BP_LOGGER_ROOKIE_CODER }}'
          
